Deface::Override.new(:virtual_path => 'spree/admin/variants/_form',
                     :name => "Add product label button",
                     :insert_bottom => ".right",
                     :partial => "spree/admin/products/barcode_variant_link",
                     :disabled => false)
Deface::Override.new(:virtual_path => 'spree/admin/variants/edit',
                     :name => "Add variant sticker",
                     :insert_after => "erb[silent]:contains('end')",
                     :partial => "spree/admin/products/stickers_variant_form",
                     :disabled => false)
Deface::Override.new(:virtual_path => 'spree/admin/products/edit',
                     :name => "Add variant label button",
                     :insert_bottom => ".right",
                     :partial => "spree/admin/products/barcode_product_link",
                     :disabled => false)
